name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build bundle
        run: npm run build

      - name: Copy bundle to release root
        run: cp dist/mini-media-player-bundle.js ./mini-media-player-bundle.js

      - name: Upload bundle to release
        uses: softprops/action-gh-release@v1
        with:
          files: mini-media-player-bundle.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
